os: Windows Server 2012
version: 0.0.1.{build}
before_build:
  - nuget restore
build:
    project: AppveyorDemo.sln
	verbosity: minimal
nuget:
  account_feed: true
  project_feed: true
deploy:
  - provider: NuGet
    symbol_server: https://ci.appveyor.com/nuget/appveyordemo-yn8bo6e9om1t
    api_key:
      secure: <secure encrypted key here>
    artifact: /.*\.symbols\.nupkg/