# configuration for "master" branch
# build in Release mode and deploy to Azure
-
  branches:
    only:
      - master

  version: 1.0.0
  configuration: Release
  os: Windows Server 2012
  platform: Any CPU

  assembly_info: 
    patch: true 
    file: AssemblyInfo.* 
    assembly_version: "{version}" 
    assembly_file_version: "{version}" 
    assembly_informational_version: "{version}"

  cache:
    - packages -> **\packages.config

  before_build:
    - nuget restore

  build:
    project: AppveyorDemo.sln
    verbosity: minimal
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
  
  test: on
  
  nuget:
    account_feed: true
    project_feed: true