os: Windows Server 2012
platform: Any CPU

assembly_info: 
  patch: true 
  file: AssemblyInfo.* 
  assembly_version: "{version}" 
  assembly_file_version: "{version}" 
  assembly_informational_version: "{version}"

before_build:
  - nuget restore

cache:
  - packages -> **\packages.config

build:
    project: AppveyorDemo.sln
    verbosity: minimal
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true

-
    branches:
        only:
            - master
    
    version: 1.0.0
    configuration: Release

-
    branches:
        only:
            - develop
    
    version: 1.0.0-beta.{version}
    configuration: Debug

-    
    branches:
        only:
            - feature/*
    
    version: 1.0.0-alpha.{version}
    configuration: Debug
  





    

nuget:
  account_feed: true
  project_feed: true