version: 1.0.0.{build}

os: Windows Server 2012
platform: AnyCPU
configuration: Release

branches:
  only:
    - master

assembly_info: 
  patch: true 
  file: AssemblyInfo.* 
  assembly_version: "{version}" 
  assembly_file_version: "{version}" 
  assembly_informational_version: "{version}"
  
before_build:
  - nuget restore

cache:
  - packages -> **\packages.config

build:
    project: AppveyorDemo.sln
    verbosity: minimal

test: on

after_test:
- nuget pack AppveyorDemo\AppveyorDemo.nuspec -Version %version%
- appveyor PushArtifact AppveyorDemo.%version%.nupkg

nuget:
  account_feed: true
  project_feed: true