# configuration for "master" branch
# build in Release mode and deploy to Azure
-
  branches:
    only:
      - master

  skip_tags: true
  version: 1.0.0.{build}
  configuration: Release
  os: Windows Server 2012
  platform: Any CPU
  

  assembly_info: 
    patch: true 
    file: AssemblyInfo.* 
    assembly_version: "{version}" 
    assembly_file_version: "{version}" 
    assembly_informational_version: "{version}"

  cache:
  - packages -> **\packages.config

  before_build:
  - cmd: appveyor AddMessage "Commited by %APPVEYOR_REPO_COMMIT_AUTHOR%"
  - cmd: appveyor AddMessage "%APPVEYOR_REPO_COMMIT_MESSAGE%"
  - cmd: appvevoy AddMessage "%APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED%"
  - nuget restore

  build:
    project: AppveyorDemo.sln
    verbosity: minimal

  test: on

  deploy_script:
  - nuget pack AppveyorDemo\AppveyorDemo.nuspec -Version %appveyor_build_version% -symbols
  - appveyor PushArtifact AppveyorDemo.%appveyor_build_version%.nupkg
  - appveyor PushArtifact AppveyorDemo.%appveyor_build_version%.symbols.nupkg
  
  nuget:
    account_feed: true
    project_feed: true
    
  notifications:
  - provider: Email
    to:
      - me@gal-segal.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true