os: Windows Server 2012
version: 0.0.1.{build}
configuration: Release

assembly_info: 
  patch: true 
  file: AssemblyInfo.* 
  assembly_version: "{version}" 
  assembly_file_version: "{version}" 
  assembly_informational_version: "{version}"
  
before_build:
  - nuget restore

build:
    project: AppveyorDemo.sln
    verbosity: minimal
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true

nuget:
  account_feed: true
  project_feed: true